use super::policy::RiskTier;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Describes how to revert or compensate for an action if execution fails or is undone.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UndoHint {
    /// The inverse tool identifier to execute (e.g. "native/set_volume", "telegram/delete_message").
    pub inverse_tool_id: String,
    /// Parameters required by the inverse tool.
    pub inverse_arguments: serde_json::Value,
    /// Human-readable explanation of the undo operation.
    pub description: String,
}

impl UndoHint {
    pub fn new(
        inverse_tool_id: impl Into<String>,
        inverse_arguments: serde_json::Value,
        description: impl Into<String>,
    ) -> Self {
        Self {
            inverse_tool_id: inverse_tool_id.into(),
            inverse_arguments,
            description: description.into(),
        }
    }
}

/// A structured proposal for an action generated by the Planner or LLM reasoning loop.
/// Proposals must be evaluated by the PolicyEngine before actual tool invocation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ActionProposal {
    /// Unique identifier for this action instance (UUID v4).
    pub action_id: String,
    /// High-level semantic intent (e.g. "adjust_room_lighting", "send_telegram_alert").
    pub intent: String,
    /// Fully-qualified tool or command identifier (e.g. "native/control_volume", "telegram:send").
    pub tool_id: String,
    /// Input parameters conforming to the tool's JSON schema.
    pub input_params: serde_json::Value,
    /// Static risk tier evaluated or proposed for this action.
    pub risk_tier: RiskTier,
    /// Planner's explicit rationale / justification for taking this action.
    pub justification: String,
    /// Cryptographic idempotency key preventing duplicate side-effects on retry/restart.
    pub idempotency_key: String,
    /// Optional compensation / rollback specification.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub undo_hint: Option<UndoHint>,
    /// Lineage link to the originating PerceptionEvent (if any).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_event_id: Option<String>,
    /// Creation timestamp in epoch milliseconds.
    pub created_at_ms: i64,
}

impl ActionProposal {
    /// Creates a new ActionProposal with auto-generated UUID, timestamp, and SHA-256 idempotency key.
    pub fn new(
        intent: impl Into<String>,
        tool_id: impl Into<String>,
        input_params: serde_json::Value,
        risk_tier: RiskTier,
        justification: impl Into<String>,
    ) -> Self {
        let intent_s = intent.into();
        let tool_id_s = tool_id.into();
        let justification_s = justification.into();
        let action_id = uuid::Uuid::new_v4().to_string();
        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        let idempotency_key =
            Self::compute_idempotency_key(&intent_s, &tool_id_s, &input_params, None);

        Self {
            action_id,
            intent: intent_s,
            tool_id: tool_id_s,
            input_params,
            risk_tier,
            justification: justification_s,
            idempotency_key,
            undo_hint: None,
            source_event_id: None,
            created_at_ms: now_ms,
        }
    }

    /// Computes a deterministic SHA-256 hash representing the action identity.
    pub fn compute_idempotency_key(
        intent: &str,
        tool_id: &str,
        input_params: &serde_json::Value,
        session_nonce: Option<&str>,
    ) -> String {
        let mut hasher = Sha256::new();
        hasher.update(intent.as_bytes());
        hasher.update(b"|");
        hasher.update(tool_id.as_bytes());
        hasher.update(b"|");
        let params_str = serde_json::to_string(input_params).unwrap_or_default();
        hasher.update(params_str.as_bytes());
        if let Some(nonce) = session_nonce {
            hasher.update(b"|");
            hasher.update(nonce.as_bytes());
        }
        let result = hasher.finalize();
        hex::encode(result)
    }

    /// Validates the proposal fields for completeness and integrity.
    pub fn validate(&self) -> Result<(), String> {
        if self.action_id.trim().is_empty() {
            return Err("action_id cannot be empty".to_string());
        }
        if self.intent.trim().is_empty() {
            return Err("intent cannot be empty".to_string());
        }
        if self.tool_id.trim().is_empty() {
            return Err("tool_id cannot be empty".to_string());
        }
        if self.idempotency_key.trim().is_empty() {
            return Err("idempotency_key cannot be empty".to_string());
        }
        if self.justification.trim().is_empty() {
            return Err("justification cannot be empty".to_string());
        }
        Ok(())
    }

    /// Fluent builder method to attach an undo hint.
    pub fn with_undo_hint(mut self, undo_hint: UndoHint) -> Self {
        self.undo_hint = Some(undo_hint);
        self
    }

    /// Fluent builder method to attach source perception event ID.
    pub fn with_source_event_id(mut self, source_event_id: impl Into<String>) -> Self {
        self.source_event_id = Some(source_event_id.into());
        self
    }

    /// Fluent builder method to override the default computed idempotency key.
    pub fn with_idempotency_key(mut self, key: impl Into<String>) -> Self {
        self.idempotency_key = key.into();
        self
    }
}
